/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

import fatec.tg1.model.Arquivo;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author MR.ROBOTNEO
 */
public class GuiEncriptarPartição extends javax.swing.JFrame {

    /**
     * Creates new form GuiEncriptarPartição
     */
    public GuiEncriptarPartição() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLEncripPart = new javax.swing.JPanel();
        jLblPartição = new javax.swing.JLabel();
        jTfdDirectory = new javax.swing.JTextField();
        jBtnBuscarPartição = new javax.swing.JButton();
        jLblSenhaEncripArq = new javax.swing.JLabel();
        jTxfSenhaEncripArq = new javax.swing.JTextField();
        jBtnEncriptarArq = new javax.swing.JButton();
        jLblSha512 = new javax.swing.JLabel();
        jBtnCopiarSha512 = new javax.swing.JButton();
        jBtnCopiarTudo = new javax.swing.JButton();
        jLblHash = new javax.swing.JLabel();
        jBtnColar = new javax.swing.JButton();
        jBtnVerificarHash = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTfdSha512 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTfdHash = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptar partição");

        jPLEncripPart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encriptar Partição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 51, 0))); // NOI18N

        jLblPartição.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblPartição.setText("Partição:");

        jBtnBuscarPartição.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/buscar partição.png"))); // NOI18N
        jBtnBuscarPartição.setText("Buscar");
        jBtnBuscarPartição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarPartiçãoActionPerformed(evt);
            }
        });

        jLblSenhaEncripArq.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLblSenhaEncripArq.setText("Senha:");

        jBtnEncriptarArq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/criptografar.png"))); // NOI18N
        jBtnEncriptarArq.setText("Encriptar");
        jBtnEncriptarArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEncriptarArqActionPerformed(evt);
            }
        });

        jLblSha512.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblSha512.setText("Sha512:");

        jBtnCopiarSha512.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/copia-de.png"))); // NOI18N
        jBtnCopiarSha512.setText("Copiar Sha512");
        jBtnCopiarSha512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCopiarSha512ActionPerformed(evt);
            }
        });

        jBtnCopiarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/copiar td.png"))); // NOI18N
        jBtnCopiarTudo.setText("Copiar Tudo");

        jLblHash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblHash.setText("Hash:");

        jBtnColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/colar.png"))); // NOI18N
        jBtnColar.setText("Colar");
        jBtnColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnColarActionPerformed(evt);
            }
        });

        jBtnVerificarHash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/senha.png"))); // NOI18N
        jBtnVerificarHash.setText("Verificar Hash");

        jTfdSha512.setColumns(20);
        jTfdSha512.setLineWrap(true);
        jTfdSha512.setRows(5);
        jScrollPane1.setViewportView(jTfdSha512);

        jTfdHash.setEditable(false);
        jTfdHash.setColumns(20);
        jTfdHash.setLineWrap(true);
        jTfdHash.setRows(5);
        jTfdHash.setBorder(null);
        jTfdHash.setOpaque(false);
        jScrollPane2.setViewportView(jTfdHash);

        javax.swing.GroupLayout jPLEncripPartLayout = new javax.swing.GroupLayout(jPLEncripPart);
        jPLEncripPart.setLayout(jPLEncripPartLayout);
        jPLEncripPartLayout.setHorizontalGroup(
            jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBtnVerificarHash)
                        .addGroup(jPLEncripPartLayout.createSequentialGroup()
                            .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLblSha512)
                                .addComponent(jLblHash, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblPartição)
                            .addComponent(jLblSenhaEncripArq, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxfSenhaEncripArq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfdDirectory))))
                .addGap(25, 25, 25)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCopiarSha512, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCopiarTudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnColar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnEncriptarArq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnBuscarPartição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnColar, jBtnCopiarSha512, jBtnCopiarTudo});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPLEncripPartLayout.setVerticalGroup(
            jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfdDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPartição)
                    .addComponent(jBtnBuscarPartição))
                .addGap(9, 9, 9)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxfSenhaEncripArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSenhaEncripArq)
                    .addComponent(jBtnEncriptarArq))
                .addGap(16, 16, 16)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jBtnVerificarHash)
                        .addContainerGap())
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLblSha512))
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addComponent(jBtnCopiarSha512)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnCopiarTudo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLEncripPartLayout.createSequentialGroup()
                                .addComponent(jBtnColar)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLEncripPartLayout.createSequentialGroup()
                                .addComponent(jLblHash)
                                .addGap(166, 166, 166))))))
        );

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnBuscarPartição, jBtnEncriptarArq});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnColar, jBtnCopiarSha512, jBtnCopiarTudo});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLEncripPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLEncripPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarPartiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarPartiçãoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getCurrentDirectory();
        String filename = f.getAbsolutePath();
        //String filename=f.get();
        jTfdDirectory.setText(filename);
    }//GEN-LAST:event_jBtnBuscarPartiçãoActionPerformed

    private void jBtnEncriptarArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEncriptarArqActionPerformed
        String senhAdmin = null;
        arquivo = new Arquivo(jTxfSenhaEncripArq.getText());
        try {
            senhAdmin = arquivo.Encriptar();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(GuiEncriptarArquivo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GuiEncriptarArquivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTfdSha512.setText(senhAdmin);
    }//GEN-LAST:event_jBtnEncriptarArqActionPerformed

    private void jBtnCopiarSha512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCopiarSha512ActionPerformed
        String text = jTfdSha512.getText();
        StringBuilder builder = new StringBuilder(text);
        builder.replace(jTfdSha512.getSelectionStart(), jTfdSha512.getSelectionEnd(),"");
    }//GEN-LAST:event_jBtnCopiarSha512ActionPerformed

    private void jBtnColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnColarActionPerformed
        String text = jTfdSha512.getText();
        StringBuilder builder = new StringBuilder(text);
        builder.replace(jTfdSha512.getSelectionStart(), jTfdSha512.getSelectionEnd(),"");
        jTfdHash.setText(text);
    }//GEN-LAST:event_jBtnColarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEncriptarPartição().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarPartição;
    private javax.swing.JButton jBtnColar;
    private javax.swing.JButton jBtnCopiarSha512;
    private javax.swing.JButton jBtnCopiarTudo;
    private javax.swing.JButton jBtnEncriptarArq;
    private javax.swing.JButton jBtnVerificarHash;
    private javax.swing.JLabel jLblHash;
    private javax.swing.JLabel jLblPartição;
    private javax.swing.JLabel jLblSenhaEncripArq;
    private javax.swing.JLabel jLblSha512;
    private javax.swing.JPanel jPLEncripPart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTfdDirectory;
    private javax.swing.JTextArea jTfdHash;
    private javax.swing.JTextArea jTfdSha512;
    private javax.swing.JTextField jTxfSenhaEncripArq;
    // End of variables declaration//GEN-END:variables
Arquivo arquivo = null;
}
