/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author MR.ROBOTNEO
 */
public class GuiEncriptarPartição extends javax.swing.JFrame {

    /**
     * Creates new form GuiEncriptarPartição
     */
    public GuiEncriptarPartição() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLEncripPart = new javax.swing.JPanel();
        jLblPartição = new javax.swing.JLabel();
        jTfdDirectory = new javax.swing.JTextField();
        jBtnBuscarPartição = new javax.swing.JButton();
        jLblSenhaEncripArq = new javax.swing.JLabel();
        jTxfSenhaEncripArq = new javax.swing.JTextField();
        jBtnEncriptarArq = new javax.swing.JButton();
        jLblSha512 = new javax.swing.JLabel();
        jTfdSha512 = new javax.swing.JTextField();
        jBtnCopiarSha512 = new javax.swing.JButton();
        jBtnCopiarTudo = new javax.swing.JButton();
        jLblHash = new javax.swing.JLabel();
        jTfdHash = new javax.swing.JTextField();
        jBtnColar = new javax.swing.JButton();
        jBtnVerificarHash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptar partição");

        jPLEncripPart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encriptar Partição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(255, 51, 0))); // NOI18N

        jLblPartição.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblPartição.setText("Partição:");

        jBtnBuscarPartição.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/buscar partição.png"))); // NOI18N
        jBtnBuscarPartição.setText("Buscar");
        jBtnBuscarPartição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarPartiçãoActionPerformed(evt);
            }
        });

        jLblSenhaEncripArq.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLblSenhaEncripArq.setText("Senha:");

        jBtnEncriptarArq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/criptografar.png"))); // NOI18N
        jBtnEncriptarArq.setText("Encriptar");

        jLblSha512.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblSha512.setText("Sha512:");

        jTfdSha512.setEnabled(false);

        jBtnCopiarSha512.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/copia-de.png"))); // NOI18N
        jBtnCopiarSha512.setText("Copiar Sha512");

        jBtnCopiarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/copiar td.png"))); // NOI18N
        jBtnCopiarTudo.setText("Copiar Tudo");

        jLblHash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblHash.setText("Hash:");

        jTfdHash.setEnabled(false);

        jBtnColar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/colar.png"))); // NOI18N
        jBtnColar.setText("Colar");

        jBtnVerificarHash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/senha.png"))); // NOI18N
        jBtnVerificarHash.setText("Verificar Hash");

        javax.swing.GroupLayout jPLEncripPartLayout = new javax.swing.GroupLayout(jPLEncripPart);
        jPLEncripPart.setLayout(jPLEncripPartLayout);
        jPLEncripPartLayout.setHorizontalGroup(
            jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                        .addComponent(jLblHash)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTfdHash, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBtnVerificarHash))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnColar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblSha512)
                                    .addComponent(jLblSenhaEncripArq, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTfdSha512)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnCopiarSha512, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnCopiarTudo)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLEncripPartLayout.createSequentialGroup()
                        .addComponent(jLblPartição)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addComponent(jTxfSenhaEncripArq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(209, 209, 209)
                                .addComponent(jBtnEncriptarArq, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                                .addComponent(jTfdDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnBuscarPartição, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnColar, jBtnCopiarSha512, jBtnCopiarTudo});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTfdHash, jTfdSha512});

        jPLEncripPartLayout.setVerticalGroup(
            jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLEncripPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnBuscarPartição)
                    .addComponent(jTfdDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPartição))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfSenhaEncripArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblSenhaEncripArq)))
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnEncriptarArq)))
                .addGap(20, 20, 20)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCopiarSha512)
                    .addComponent(jLblSha512)
                    .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTfdSha512, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCopiarTudo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLEncripPartLayout.createSequentialGroup()
                        .addGroup(jPLEncripPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblHash)
                            .addComponent(jTfdHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLEncripPartLayout.createSequentialGroup()
                        .addComponent(jBtnColar)
                        .addGap(3, 3, 3)))
                .addComponent(jBtnVerificarHash)
                .addGap(6, 6, 6))
        );

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnBuscarPartição, jBtnEncriptarArq});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnColar, jBtnCopiarSha512, jBtnCopiarTudo});

        jPLEncripPartLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTfdHash, jTfdSha512});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPLEncripPart, javax.swing.GroupLayout.PREFERRED_SIZE, 735, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPLEncripPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarPartiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarPartiçãoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getCurrentDirectory();
        String filename = f.getAbsolutePath();
        //String filename=f.get();
        jTfdDirectory.setText(filename);
    }//GEN-LAST:event_jBtnBuscarPartiçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEncriptarPartição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEncriptarPartição().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarPartição;
    private javax.swing.JButton jBtnColar;
    private javax.swing.JButton jBtnCopiarSha512;
    private javax.swing.JButton jBtnCopiarTudo;
    private javax.swing.JButton jBtnEncriptarArq;
    private javax.swing.JButton jBtnVerificarHash;
    private javax.swing.JLabel jLblHash;
    private javax.swing.JLabel jLblPartição;
    private javax.swing.JLabel jLblSenhaEncripArq;
    private javax.swing.JLabel jLblSha512;
    private javax.swing.JPanel jPLEncripPart;
    private javax.swing.JTextField jTfdDirectory;
    private javax.swing.JTextField jTfdHash;
    private javax.swing.JTextField jTfdSha512;
    private javax.swing.JTextField jTxfSenhaEncripArq;
    // End of variables declaration//GEN-END:variables
}
