/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

import fatec.tg1.model.Arquivo;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class GuiEncripDescripTxt1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiEncripDescripTxt1
     */
    public GuiEncripDescripTxt1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlEncDescTxt = new javax.swing.JPanel();
        jBtnEncrpTxt = new javax.swing.JButton();
        jBtnDescripTxt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxfEncripTxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxfDescripTxt = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Encriptar/Descriptar Texto");

        jPnlEncDescTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encriptar/Descriptar Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(204, 51, 0))); // NOI18N
        jPnlEncDescTxt.setToolTipText("");

        jBtnEncrpTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/criptografar.png"))); // NOI18N
        jBtnEncrpTxt.setText("Encriptar");
        jBtnEncrpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEncrpTxtActionPerformed(evt);
            }
        });

        jBtnDescripTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/descriptografar.png"))); // NOI18N
        jBtnDescripTxt.setText("Descriptar");

        jTxfEncripTxt.setColumns(20);
        jTxfEncripTxt.setLineWrap(true);
        jTxfEncripTxt.setRows(5);
        jScrollPane1.setViewportView(jTxfEncripTxt);

        jTxfDescripTxt.setColumns(20);
        jTxfDescripTxt.setLineWrap(true);
        jTxfDescripTxt.setRows(5);
        jScrollPane2.setViewportView(jTxfDescripTxt);

        javax.swing.GroupLayout jPnlEncDescTxtLayout = new javax.swing.GroupLayout(jPnlEncDescTxt);
        jPnlEncDescTxt.setLayout(jPnlEncDescTxtLayout);
        jPnlEncDescTxtLayout.setHorizontalGroup(
            jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncDescTxtLayout.createSequentialGroup()
                .addGroup(jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnEncrpTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnDescripTxt, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPnlEncDescTxtLayout.setVerticalGroup(
            jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncDescTxtLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEncrpTxt)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDescripTxt))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlEncDescTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPnlEncDescTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEncrpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEncrpTxtActionPerformed
        String senhAdmin = null;
        arquivo = new Arquivo(jTxfEncripTxt.getText());
        try {
            senhAdmin = arquivo.Encriptar();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(GuiEncriptarArquivo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GuiEncriptarArquivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTxfEncripTxt.setText(senhAdmin);
    }//GEN-LAST:event_jBtnEncrpTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDescripTxt;
    private javax.swing.JButton jBtnEncrpTxt;
    private javax.swing.JPanel jPnlEncDescTxt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxfDescripTxt;
    private javax.swing.JTextArea jTxfEncripTxt;
    // End of variables declaration//GEN-END:variables
    Arquivo arquivo = null;
}
