/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

/**
 *
 * @author MR.ROBOTNEO
 */
public class GuiEncripDescripTxt extends javax.swing.JFrame {

    /**
     * Creates new form GuiEncripDescripTxt
     */
    public GuiEncripDescripTxt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlEncDescTxt = new javax.swing.JPanel();
        jTxfEncripTxt = new javax.swing.JTextField();
        jBtnEncrpTxt = new javax.swing.JButton();
        jTxfDescripTxt = new javax.swing.JTextField();
        jBtnDescripTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encriptar e Descriptar Texto");

        jPnlEncDescTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encriptar/Descriptar Texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13), new java.awt.Color(204, 51, 0))); // NOI18N
        jPnlEncDescTxt.setToolTipText("");

        jBtnEncrpTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/criptografar.png"))); // NOI18N
        jBtnEncrpTxt.setText("Encriptar");

        jBtnDescripTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/tg1/view/icon/descriptografar.png"))); // NOI18N
        jBtnDescripTxt.setText("Descriptar");

        javax.swing.GroupLayout jPnlEncDescTxtLayout = new javax.swing.GroupLayout(jPnlEncDescTxt);
        jPnlEncDescTxt.setLayout(jPnlEncDescTxtLayout);
        jPnlEncDescTxtLayout.setHorizontalGroup(
            jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncDescTxtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxfDescripTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                        .addComponent(jTxfEncripTxt)
                        .addComponent(jBtnEncrpTxt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jBtnDescripTxt))
                .addContainerGap())
        );
        jPnlEncDescTxtLayout.setVerticalGroup(
            jPnlEncDescTxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEncDescTxtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTxfEncripTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEncrpTxt)
                .addGap(18, 18, 18)
                .addComponent(jTxfDescripTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnDescripTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlEncDescTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlEncDescTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 674, Short.MAX_VALUE)
        );

        jPnlEncDescTxt.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiEncripDescripTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiEncripDescripTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiEncripDescripTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiEncripDescripTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiEncripDescripTxt().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDescripTxt;
    private javax.swing.JButton jBtnEncrpTxt;
    private javax.swing.JPanel jPnlEncDescTxt;
    private javax.swing.JTextField jTxfDescripTxt;
    private javax.swing.JTextField jTxfEncripTxt;
    // End of variables declaration//GEN-END:variables
}
