/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

/**
 *
 * @author MR.ROBOTNEO
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jCbxEncriptarArq = new javax.swing.JCheckBoxMenuItem();
        jCbxDescripArq = new javax.swing.JCheckBoxMenuItem();
        jMenuPartição = new javax.swing.JMenu();
        jMenuEncriptPart = new javax.swing.JCheckBoxMenuItem();
        jMenuDescripPart = new javax.swing.JCheckBoxMenuItem();
        jMenuTexto = new javax.swing.JMenu();
        jMenuEncripDecsripTxt = new javax.swing.JCheckBoxMenuItem();
        jMenuBackup = new javax.swing.JMenu();
        jMenuGerarBackup = new javax.swing.JCheckBoxMenuItem();
        jMenuRestBD = new javax.swing.JCheckBoxMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        jMenuArquivo.setText("Arquivo");

        jCbxEncriptarArq.setSelected(true);
        jCbxEncriptarArq.setText("Encriptar");
        jCbxEncriptarArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxEncriptarArqActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jCbxEncriptarArq);

        jCbxDescripArq.setSelected(true);
        jCbxDescripArq.setText("Descriptar");
        jCbxDescripArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxDescripArqActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jCbxDescripArq);

        jMenuBar1.add(jMenuArquivo);

        jMenuPartição.setText("Partição");

        jMenuEncriptPart.setSelected(true);
        jMenuEncriptPart.setText("Encriptar");
        jMenuEncriptPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEncriptPartActionPerformed(evt);
            }
        });
        jMenuPartição.add(jMenuEncriptPart);

        jMenuDescripPart.setSelected(true);
        jMenuDescripPart.setText("Descriptar");
        jMenuDescripPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDescripPartActionPerformed(evt);
            }
        });
        jMenuPartição.add(jMenuDescripPart);

        jMenuBar1.add(jMenuPartição);

        jMenuTexto.setText("Texto");

        jMenuEncripDecsripTxt.setSelected(true);
        jMenuEncripDecsripTxt.setText("Encriptar/Descriptar");
        jMenuEncripDecsripTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEncripDecsripTxtActionPerformed(evt);
            }
        });
        jMenuTexto.add(jMenuEncripDecsripTxt);

        jMenuBar1.add(jMenuTexto);

        jMenuBackup.setText("Backup");

        jMenuGerarBackup.setSelected(true);
        jMenuGerarBackup.setText("Gerar Backup");
        jMenuGerarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarBackupActionPerformed(evt);
            }
        });
        jMenuBackup.add(jMenuGerarBackup);

        jMenuRestBD.setSelected(true);
        jMenuRestBD.setText("Restaurar Base de Dados");
        jMenuRestBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestBDActionPerformed(evt);
            }
        });
        jMenuBackup.add(jMenuRestBD);

        jMenuBar1.add(jMenuBackup);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbxEncriptarArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxEncriptarArqActionPerformed
        new GuiEncriptarArquivo().setVisible(true);
    }//GEN-LAST:event_jCbxEncriptarArqActionPerformed

    private void jCbxDescripArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxDescripArqActionPerformed
        new GuiDescriptarArquivo().setVisible(true);
    }//GEN-LAST:event_jCbxDescripArqActionPerformed

    private void jMenuEncriptPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEncriptPartActionPerformed
        new GuiEncriptarPartição().setVisible(true);
    }//GEN-LAST:event_jMenuEncriptPartActionPerformed

    private void jMenuDescripPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDescripPartActionPerformed
        new GuiDescriptarPartição().setVisible(true);
    }//GEN-LAST:event_jMenuDescripPartActionPerformed

    private void jMenuEncripDecsripTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEncripDecsripTxtActionPerformed
        new GuiEncripDescripTxt().setVisible(true);
    }//GEN-LAST:event_jMenuEncripDecsripTxtActionPerformed

    private void jMenuGerarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarBackupActionPerformed
        new GuiGerarBackup().setVisible(true);
    }//GEN-LAST:event_jMenuGerarBackupActionPerformed

    private void jMenuRestBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestBDActionPerformed
        new GuiRestaurarBD(). setVisible(true);
    }//GEN-LAST:event_jMenuRestBDActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCbxDescripArq;
    private javax.swing.JCheckBoxMenuItem jCbxEncriptarArq;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenu jMenuBackup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem jMenuDescripPart;
    private javax.swing.JCheckBoxMenuItem jMenuEncripDecsripTxt;
    private javax.swing.JCheckBoxMenuItem jMenuEncriptPart;
    private javax.swing.JCheckBoxMenuItem jMenuGerarBackup;
    private javax.swing.JMenu jMenuPartição;
    private javax.swing.JCheckBoxMenuItem jMenuRestBD;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTexto;
    // End of variables declaration//GEN-END:variables
}
