/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.tg1.view;

import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author MR.ROBOTNEO
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblData = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jCbxEncriptarArq = new javax.swing.JCheckBoxMenuItem();
        jCbxDescripArq = new javax.swing.JCheckBoxMenuItem();
        jMenuPartição = new javax.swing.JMenu();
        jMenuEncriptPart = new javax.swing.JCheckBoxMenuItem();
        jMenuDescripPart = new javax.swing.JCheckBoxMenuItem();
        jMenuTexto = new javax.swing.JMenu();
        jMenuEncripDecsripTxt = new javax.swing.JCheckBoxMenuItem();
        menuBackup = new javax.swing.JMenu();
        jMenuGerarBackup = new javax.swing.JCheckBoxMenuItem();
        jMenuRestBD = new javax.swing.JCheckBoxMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Data");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário");

        lblPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPerfil.setText("Administrador");

        lblUsuario1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario1.setText("Usuário:");

        jMenuArquivo.setText("Arquivo");

        jCbxEncriptarArq.setSelected(true);
        jCbxEncriptarArq.setText("Encriptar");
        jCbxEncriptarArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxEncriptarArqActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jCbxEncriptarArq);

        jCbxDescripArq.setSelected(true);
        jCbxDescripArq.setText("Descriptar");
        jCbxDescripArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxDescripArqActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jCbxDescripArq);

        jMenuBar1.add(jMenuArquivo);

        jMenuPartição.setText("Partição");

        jMenuEncriptPart.setSelected(true);
        jMenuEncriptPart.setText("Encriptar");
        jMenuEncriptPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEncriptPartActionPerformed(evt);
            }
        });
        jMenuPartição.add(jMenuEncriptPart);

        jMenuDescripPart.setSelected(true);
        jMenuDescripPart.setText("Descriptar");
        jMenuDescripPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDescripPartActionPerformed(evt);
            }
        });
        jMenuPartição.add(jMenuDescripPart);

        jMenuBar1.add(jMenuPartição);

        jMenuTexto.setText("Texto");

        jMenuEncripDecsripTxt.setSelected(true);
        jMenuEncripDecsripTxt.setText("Encriptar/Descriptar");
        jMenuEncripDecsripTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEncripDecsripTxtActionPerformed(evt);
            }
        });
        jMenuTexto.add(jMenuEncripDecsripTxt);

        jMenuBar1.add(jMenuTexto);

        menuBackup.setText("Backup");

        jMenuGerarBackup.setSelected(true);
        jMenuGerarBackup.setText("Gerar Backup");
        jMenuGerarBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerarBackupActionPerformed(evt);
            }
        });
        menuBackup.add(jMenuGerarBackup);

        jMenuRestBD.setSelected(true);
        jMenuRestBD.setText("Restaurar Base de Dados");
        jMenuRestBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestBDActionPerformed(evt);
            }
        });
        menuBackup.add(jMenuRestBD);

        jMenuBar1.add(menuBackup);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuario)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblUsuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbxEncriptarArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxEncriptarArqActionPerformed
        new GuiEncriptarArquivo().setVisible(true);
    }//GEN-LAST:event_jCbxEncriptarArqActionPerformed

    private void jCbxDescripArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxDescripArqActionPerformed
        new GuiDescriptarArquivo().setVisible(true);
    }//GEN-LAST:event_jCbxDescripArqActionPerformed

    private void jMenuEncriptPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEncriptPartActionPerformed
        new GuiEncriptarPartição().setVisible(true);
    }//GEN-LAST:event_jMenuEncriptPartActionPerformed

    private void jMenuDescripPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDescripPartActionPerformed
        new GuiDescriptarPartição().setVisible(true);
    }//GEN-LAST:event_jMenuDescripPartActionPerformed

    private void jMenuEncripDecsripTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEncripDecsripTxtActionPerformed
        new GuiEncripDescripTxt().setVisible(true);
    }//GEN-LAST:event_jMenuEncripDecsripTxtActionPerformed

    private void jMenuGerarBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerarBackupActionPerformed
        new GuiGerarBackup().setVisible(true);
    }//GEN-LAST:event_jMenuGerarBackupActionPerformed

    private void jMenuRestBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestBDActionPerformed
        new GuiRestaurarBD(). setVisible(true);
    }//GEN-LAST:event_jMenuRestBDActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // ao ativar a janela, mude e atualize a data:
        Date data = new Date();
        // formatando a data
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JCheckBoxMenuItem jCbxDescripArq;
    private javax.swing.JCheckBoxMenuItem jCbxEncriptarArq;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem jMenuDescripPart;
    private javax.swing.JCheckBoxMenuItem jMenuEncripDecsripTxt;
    private javax.swing.JCheckBoxMenuItem jMenuEncriptPart;
    private javax.swing.JCheckBoxMenuItem jMenuGerarBackup;
    private javax.swing.JMenu jMenuPartição;
    private javax.swing.JCheckBoxMenuItem jMenuRestBD;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuTexto;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JLabel lblUsuario1;
    public static javax.swing.JMenu menuBackup;
    // End of variables declaration//GEN-END:variables
}
